default:win
gcc:
	gcc -std=gnu99 -Wall -Wno-unused-variable -Wno-unused-function -pedantic -g -x c test_yarn_size.cpp ../../src/woven_cloth.cpp -o test_yarn_size.bin
win:
	cl test_yarn_size.cpp ../../src/woven_cloth.cpp /Zi /nologo
