default:win
gcc:
	gcc -std=gnu99 -Wall -pedantic -g -x c test_calculate_segment_size.cpp ../../src/woven_cloth.cpp -o test_calculate_segment_size
win:
	cl test_calculate_segment_size.cpp ../../src/woven_cloth.cpp /Zi /nologo
