default:win
gcc:
	gcc -Wall -pedantic -Wno-unused-variable -Wno-unused-function test_calculate_segment_size.cpp -g -o test_calculate_segment_size.bin
win:
	cl test_calculate_segment_size.cpp /Zi /nologo
