default:win
gcc:
	gcc -std=gnu99 -Wall -pedantic -Wno-unused-variable -Wno-unused-function -g -x c test_calculate_segment_size.cpp ../../src/woven_cloth.cpp -o test_calculate_segment_size.bin
win:
	cl test_calculate_segment_size.cpp ../../src/woven_cloth.cpp /Zi /nologo
