default:build run

compiler_flags = -g
warnings = -Wall -Weverything -Wno-padded
#optimization  = -O0
#optimization = -Os
optimization  = -O1 -fsanitize=address -fno-omit-frame-pointer

build:
	clang main.c ini.c wif.c $(compiler_flags) $(warnings) $(optimization)\
	   	-o wif_reader

run:
	./wif_reader
