//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by vrayblinnmtl.rc
//
#define IDS_CLASSNAME                   1
#define IDS_PARAMETERS                  2
#define IDS_SIMPLE                      3
#define IDS_LIBDESC                     4
#define IDS_MTL1                        5
#define ids_baseMtl                     5
#define IDS_MTL1ON                      6
#define ids_baseMtl_on                  6
#define IDS_YARN                        6
#define ids_giMtl                       7
#define ids_coatMtl                     7
#define ids_giMtl_on                    8
#define IDS_PATTERN                     8
#define ids_reflectMtl                  9
#define IDS_LOAD_PATTERN_FILE           9
#define ids_reflectMtl_on               10
#define IDS_LOAD_PATTERN_FILE_TYPES     10
#define ids_refractMtl                  11
#define ids_refractMtl_on               12
#define ids_blend                       13
#define ids_texmap_blend                14
#define ids_texmap_blend_mult           15
#define ids_texmap_blend_on             16
#define ids_additive                    17
#define bm_MTL                          101
#define IDB_BITMAP2                     102
#define bm_MTLMASK                      102
#define bm_POWERSHADER                  104
#define IDB_LOGO                        107
#define st_coat1                        1001
#define st_coat2                        1002
#define st_coat3                        1003
#define st_coat4                        1004
#define st_coat5                        1005
#define st_coat6                        1006
#define st_coat7                        1007
#define st_coat8                        1008
#define st_coat9                        1009
#define cb_additive                     1010
#define IDC_specular_strength_EDIT      1011
#define IDC_CHECK1                      1012
#define IDC_USCALE_EDIT                 1013
#define IDC_umax_OVERRIDE               1014
#define IDC_specular_strength_SPIN      1015
#define IDC_USCALE_SPIN                 1016
#define IDC_yarnsize_OVERRIDE           1016
#define IDC_VSCALE_EDIT                 1017
#define IDC_specular_strength_SPIN2     1017
#define IDC_VSCALE_SPIN                 1018
#define IDC_umax_EDIT                   1019
#define IDC_UVROTATION_EDIT             1019
#define IDC_umax_SPIN                   1020
#define IDC_VSCALE_SPIN2                1020
#define IDC_UVROTATION_SPIN             1020
#define IDC_VERSION                     1021
#define IDC_yarnsize_EDIT               1021
#define IDC_PATTERN_GROUP               1022
#define IDC_umax_SPIN2                  1022
#define IDC_yarnsize_SPIN               1022
#define IDC_USCALE_LABEL                1023
#define IDC_VSCALE_LABEL                1024
#define IDC_REALWORLD_LABEL             1025
#define IDC_REALWORLD_CHECK             1026
#define IDC_umax_LABEL                  1027
#define IDC_VSCALE_LABEL4               1027
#define IDC_VSCALE_LABEL2               1028
#define IDC_psi_LABEL                   1029
#define IDC_VSCALE_LABEL3               1030
#define IDC_psi_EDIT                    1031
#define IDC_SPECNOISE_LABEL             1032
#define IDC_psi_SPIN                    1033
#define IDC_delta_x_EDIT                1034
#define IDC_delta_x_SPIN                1035
#define IDC_SIMPLE_EDIT                 1036
#define cs_blend1                       1037
#define IDC_delta_x_LABEL               1038
#define ed_texmap_blend_mult1           1039
#define IDC_alpha_LABEL                 1040
#define cs_blend2                       1041
#define IDC_alpha_EDIT                  1042
#define ed_texmap_blend_mult2           1043
#define IDC_alpha_SPIN                  1044
#define cs_blend3                       1045
#define IDC_alpha_LABEL2                1046
#define ed_texmap_blend_mult3           1047
#define IDC_beta_EDIT                   1048
#define cs_blend4                       1049
#define IDC_beta_SPIN                   1050
#define ed_texmap_blend_mult4           1051
#define IDC_USCALE_LABEL2               1052
#define IDC_WIFFILE_LABEL               1053
#define cs_blend5                       1054
#define IDC_WIFFILE_BUTTON              1055
#define IDC_YRN_TEX_SPECULAR_BUTTON     1056
#define IDC_PATTERNEDITOR_BUTTON        1056
#define ed_texmap_blend_mult5           1057
#define IDC_YARNTYPE_COMBO              1058
#define cs_blend6                       1059
#define IDC_YARNTYPE_LABEL              1060
#define ed_texmap_blend_mult6           1061
#define IDC_YRN_TEX_DIFFUSE_BUTTON      1062
#define cs_blend7                       1063
#define IDC_color_SWATCH                1064
#define ed_texmap_blend_mult7           1065
#define IDC_specular_color_SWATCH       1065
#define IDC_YRN_TEX_specular_strength_LABEL 1066
#define IDC_CUSTOM1                     1067
#define cs_blend8                       1068
#define IDC_YRN_TEX_SIZE_LABEL          1069
#define IDD_SKELETON_MATERIAL           1070
#define IDD_BLENDMTL                    1071
#define ed_texmap_blend_mult8           1072
#define IDC_YRN_TEX_SIZE_BUTTON         1073
#define IDC_psi_OVERRIDE                1074
#define cs_blend9                       1075
#define IDD_BLENDMTL1                   1076
#define IDD_PARAMS                      1077
#define IDD_YARN                        1078
#define IDC_delta_x_OVERRIDE            1079
#define ed_texmap_blend_mult9           1080
#define IDD_BLENDMTL2                   1081
#define IDC_YRN_TEX_DIFFUSE_LABEL       1082
#define IDD_YARN_TYPE                   1083
#define IDC_specular_strength_OVERRIDE  1085
#define IDC_alpha_OVERRIDE              1086
#define IDC_beta_OVERRIDE               1087
#define IDC_SIMPLE_SPIN                 1088
#define IDC_color_OVERRIDE              1089
#define sp_texmap_blend_mult1           1090
#define IDC_specular_color_OVERRIDE     1090
#define IDC_YRN_TEX_SIZE_BUTTON2        1091
#define sp_texmap_blend_mult2           1092
#define IDC_YRN_TEX_DIFFUSE_LABEL2      1093
#define IDC_specular_noise_EDIT         1094
#define sp_texmap_blend_mult3           1094
#define IDC_specular_noise_SPIN         1095
#define sp_texmap_blend_mult4           1095
#define IDC_specular_noise_OVERRIDE     1096
#define sp_texmap_blend_mult5           1096
#define IDC_SPECU_OVERRIDE              1096
#define sp_texmap_blend_mult6           1097
#define sp_texmap_blend_mult7           1098
#define sp_texmap_blend_mult8           1099
#define IDC_MTL1                        1100
#define bn_baseMtl                      1101
#define bn_giMtl                        1102
#define bn_coatMtl1                     1103
#define bn_reflectMtl                   1104
#define bn_texmap_blend1                1105
#define bn_refractMtl                   1106
#define bn_coatMtl2                     1107
#define bn_texmap_blend2                1108
#define bn_coatMtl3                     1109
#define bn_texmap_blend3                1110
#define bn_coatMtl4                     1111
#define bn_texmap_blend4                1112
#define bn_coatMtl5                     1113
#define bn_texmap_blend5                1114
#define bn_coatMtl6                     1115
#define bn_texmap_blend6                1116
#define bn_coatMtl7                     1117
#define bn_texmap_blend7                1118
#define bn_coatMtl8                     1119
#define bn_texmap_blend8                1120
#define bn_coatMtl9                     1121
#define sp_texmap_blend_mult9           1122
#define bn_texmap_blend9                1123
#define IDC_TEX_DIFFUSE_BUTTON          1124
#define IDC_TEX_DIFFUSE_BUTTON2         1125
#define IDC_TEX_specular_strength_BUTTON 1126
#define IDR_MENU_TEX_CLEAR              1127
#define IDC_SPECULARNOISE_EDIT          1128
#define IDC_SPECULARNOISE_SPIN          1129
#define IDC_MTLON1                      1130
#define cb_giMtl                        1131
#define cb_reflectMtl                   1132
#define cb_refractMtl                   1133
#define IDC_YRN_TEX_color_BUTTON        1197
#define IDC_YRN_TEX_specular_strength_BUTTON 1199
#define IDC_YRN_TEX_yarnsize_BUTTON     1200
#define IDC_YRN_TEX_specular_color_BUTTON 1202

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        112
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1203
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
